name: Laravel + Blade CI/CD

on:
  push:
    branches: ["staging"]
  pull_request:
    branches: ["staging"]

jobs:
  laravel-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 5804
          script: |
            /home/segnwyff/ecom  
            git checkout .
            git pull origin staging
            php artisan optimize:clear
            php artisan cache:clear
            php artisan config:clear
            php artisan view:clear